### ISSUE TITLE
Can't create new devices

### ISSUE THREAD

**Issue by FedeG** [lelylan/devices#64]
##### Detail:
When I send request to create a device, I receive Internal Server Error.

##### Curl command to create a device:
```bash
curl -X POST http://api-proxy/devices \
     -H 'Authorization: Bearer d67195569fb3fa2acedf8e318c442fd1b9fb47f8d109181be215b01e62029d5e' \
     -H 'Content-Type: application/json' \
     -d '{
           "name": "Alarma 1",
           "type": { "id": "58890ffce8cc35347a000001" }
         }'
```

##### Proxy log:
```bash
nginx-proxy_1    | nginx.1    | api-proxy 172.19.0.1 - - [25/Jan/2017:21:10:43 +0000] "POST /devices HTTP/1.1" 500 19429 "-" "curl/7.47.0"
devices_1        | 21:10:43 web.1  | 172.19.0.1,172.19.0.3 - - [25/Jan/2017 21:10:43] "POST /devices HTTP/1.1" 500 19429 0.0764
```

##### Device microservice logs:
```bash
devices_1        | 21:10:43 web.1  |   MOPED: 172.19.0.5:27017 QUERY        database=people collection=oauth_access_tokens selector={"$query"=>{"token"=>"d67195569fb3fa2acedf8e318c442fd1b9fb47f8d109181be215b01e62029d5e"}, "$orderby"=>{:_id=>1}} flags=[:slave_ok] limit=-1 skip=0 batch_size=nil fields=nil (1.4741ms)
devices_1        | 21:10:43 web.1  |   MOPED: 172.19.0.5:27017 QUERY        database=people collection=users selector={"_id"=>"58890d8685b9b33aa7000001"} flags=[:slave_ok] limit=0 skip=0 batch_size=nil fields=nil (1.2710ms)
devices_1        | 21:10:43 web.1  |
devices_1        | 21:10:43 web.1  |
devices_1        | 21:10:43 web.1  | Started POST "/devices" for 172.19.0.15 at 2017-01-25 21:10:43 +0000
devices_1        | 21:10:43 web.1  | Processing by DevicesController#create as JSON
devices_1        | 21:10:43 web.1  |   Parameters: {"name"=>"Alarma 1", "type"=>{"id"=>"58890ffce8cc35347a000001"}}
devices_1        | 21:10:43 web.1  |   MOPED: 172.19.0.5:27017 QUERY        database=people collection=oauth_access_tokens selector={"$query"=>{"token"=>"d67195569fb3fa2acedf8e318c442fd1b9fb47f8d109181be215b01e62029d5e"}, "$orderby"=>{:_id=>1}} flags=[:slave_ok] limit=-1 skip=0 batch_size=nil fields=nil (0.9303ms)
devices_1        | 21:10:43 web.1  |   MOPED: 172.19.0.5:27017 QUERY        database=people collection=users selector={"_id"=>"58890d8685b9b33aa7000001"} flags=[:slave_ok] limit=0 skip=0 batch_size=nil fields=nil (0.4950ms)
devices_1        | 21:10:43 web.1  | WARNING: Can't mass-assign protected attributes: format, action, controller
devices_1        | 21:10:43 web.1  | Completed 500 Internal Server Error in 13ms
devices_1        | 21:10:43 web.1  |
devices_1        | 21:10:43 web.1  | NoMethodError (undefined method `match' for nil:NilClass):
devices_1        | 21:10:43 web.1  |   app/models/device.rb:86:in `touch_locations'
devices_1        | 21:10:43 web.1  |   app/controllers/devices_controller.rb:32:in `create'
devices_1        | 21:10:43 web.1  |   lib/middlewares/hostable.rb:8:in `call'
devices_1        | 21:10:43 web.1  |   lib/middlewares/daily_rate_limit.rb:8:in `call'
devices_1        | 21:10:43 web.1  |
devices_1        | 21:10:43 web.1  |
devices_1        | 21:10:43 web.1  |   Rendered /var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
devices_1        | 21:10:43 web.1  |   Rendered /var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
devices_1        | 21:10:43 web.1  |   Rendered /var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (18.2ms)
```

##### Type _**58890ffce8cc35347a000001**_ exists:
```bash
curl http://api-proxy/types  \
    -H 'Authorization: Bearer d67195569fb3fa2acedf8e318c442fd1b9fb47f8d109181be215b01e62029d5e'

[{"id":"58891181e8cc35347a000002","uri":"http://api-proxy/types/58891181e8cc35347a000002","name":"Alarma 1","category":null,"owner":{"id":"58890d8685b9b33aa7000001","uri":"http://api-proxy/people/58890d8685b9b33aa7000001"},"description":"","created_at":"2017-01-25T20:58:41Z","updated_at":"2017-01-25T20:58:41Z"},{"id":"58890ffce8cc35347a000001","uri":"http://api-proxy/types/58890ffce8cc35347a000001","name":"Light","category":null,"owner":{"id":"58890d8685b9b33aa7000001","uri":"http://api-proxy/people/58890d8685b9b33aa7000001"},"description":"","created_at":"2017-01-25T20:52:12Z","updated_at":"2017-01-25T20:52:12Z"}]
```

This error are occurred in this line: [link](https://github.com/lelylan/devices/blob/master/app/models/device.rb#L86)

**Comment by andreareginato** [comment]
@FedeG Location is a model that should be removed. It's not used anymore.

**Comment by FedeG** [comment]
Can you remove the location model or say me where remove it?

**Comment by andreareginato** [comment]
@FedeG, If you can remove it would be great. Thanks
